name: Tests

on:
  push:
  pull_request:
  schedule:
  - cron: '0 4 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2]
        laravel: [10.*]
        phpunit: [9.6]
        dependency-version: [prefer-stable]
        include:
        - laravel: 10.*
          phpunit: 9.6
        - laravel: 9.*
          phpunit: 9.6

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Librdkafka
      run: |
        wget -qO - https://packages.confluent.io/deb/5.4/archive.key | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.4 stable main"
        sudo apt-get update
        sudo apt-get install librdkafka-dev

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, pecl
        extensions: curl, libxml, mbstring, zip, bcmath, rdkafka
        coverage: pcov

    - name: Install dependencies
      run: |
        composer remove phpro/grumphp --no-interaction --no-update --dev
        composer require "laravel/framework:${{ matrix.laravel }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

    - name: Execute Unit Tests
      run: composer test -- --coverage-clover coverage/coverage.xml

    #- name: Check PSR-12 Codestyle
    #  run: composer lint 

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: RamiiYoussef/laravel-kafka
        version: "v0.1.15"